/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockDiamondSol from "./MockDiamond.sol";
export { MockTestFacet__factory } from "./MockTestFacet__factory";
