/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockDiamondSol from "./MockDiamond.sol";
export type { mockDiamondSol };
export type { MockTestFacet } from "./MockTestFacet";
export * as factories from "./factories";
export type { IDiamondCut } from "./MockDiamond.sol/IDiamondCut";
export { IDiamondCut__factory } from "./factories/MockDiamond.sol/IDiamondCut__factory";
export type { IDiamondLoupe } from "./MockDiamond.sol/IDiamondLoupe";
export { IDiamondLoupe__factory } from "./factories/MockDiamond.sol/IDiamondLoupe__factory";
export type { IERC165 } from "./MockDiamond.sol/IERC165";
export { IERC165__factory } from "./factories/MockDiamond.sol/IERC165__factory";
export type { MockDiamond } from "./MockDiamond.sol/MockDiamond";
export { MockDiamond__factory } from "./factories/MockDiamond.sol/MockDiamond__factory";
export { MockTestFacet__factory } from "./factories/MockTestFacet__factory";
